# Generated by Django 5.2.6 on 2025-09-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_message_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pref_gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Anyone', 'Anyone')], default='Anyone', max_length=10),
        ),
    ]
